applications:
  - name: diff-so-fancy
    repo:
      github: https://github.com/so-fancy/diff-so-fancy
    packages:
      homebrew: diff-so-fancy
    tags:
      - diff visualizer
  - name: GitHub CLI
    repo:
      github:
    packages:
      homebrew: gh
    tags:
      - git client
      - github
  - name: Source Tree
    repo:
      github: https://github.com/GNOME/meld
    packages:
      homebrew:
        - sourcetree
    tags:
      - git client
      - gui
vscode:
  extensions:
    - name: GitHub Pull Requests
      id: github.vscode-pull-request-github
      github: https://github.com/Microsoft/vscode-pull-request-github
      marketplace: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github
      tags:
        - version control
    - name: GitHub Copilot Chat
      id: GitHub.copilot-chat
      github: https://github.com/microsoft/vscode-copilot-chat
      marketplace: https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat
      tags:
        - ai assistant
