[project]
name = "my-playbooks"
version = "0.6.0"
description = "Workstation configuration management with Ansible."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ansible>=13.1.0",
    "commitizen>=4.10.1",
    "pre-commit>=4.5.1",
    "shellcheck-py>=0.11.0.1",
]
