[project]
name = "my-playbooks"
version = "0.1.0"
description = "Workstation configuration management with Ansible."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ansible>=13.1.0"
]
