applications:
  - name: Conda
    description: Python version and package manager.
    docs: https://www.anaconda.com/docs/getting-started/miniconda/main
    repo:
      github: https://github.com/conda/conda
    packages:
      homebrew: miniconda
    tags:
      - version manager
      - package manager
      - environment manager
      - python
  - name: Deno
    docs: https://docs.deno.com/runtime/
    repo: https://github.com/denoland/deno
    packages:
      homebrew: deno
    tags:
      - javascript
      - typescript
      - web assembly
      - version management
  - name: diff-so-fancy
    repo:
      github: https://github.com/so-fancy/diff-so-fancy
    packages:
      homebrew: diff-so-fancy
    tags:
      - diff visualizer
      - diff tool
      - git enhancement
  - name: GitHub CLI
    repo:
      github:
    packages:
      homebrew: gh
    tags:
      - git client
      - github
  - name: Dyff
    description: A YAML diff tool that makes it easy to see what changed between files.
    docs: https://github.com/homeport/dyff/blob/main/.docs/commands/dyff.md
    repo: https://github.com/homeport/dyff
    packages:
      homebrew: homeport/tap/dyff
    tags:
      - diff tool
      - yaml diff tool
      - yaml
  - name: Gnome Meld
    description: Visual diff and merge tool for files, directories, and git projects.
    docs: https://meld.app/
    repo: https://github.com/GNOME/meld
    packages:
      homebrew: meld
    tags:
      - diff tool
      - gui application
      - command line tool
  - name: Node Version Manager (nvm)
    docs:
    repo: https://github.com/nvm-sh/nvm
    packages:
      homebrew: nvm
    tags:
      - javascript
      - version management
  - name: ShellCheck
    description: Static analysis tool for shell scripts.
    docs: https://www.shellcheck.net/
    repo: https://github.com/koalaman/shellcheck
    packages:
      homebrew: shellcheck
    tags:
      - bash
      - linter
  - name: shfmt
    description: Bash script formatter.
    repo: https://github.com/patrickvane/shfmt
    packages:
      homebrew: shfmt
    tags:
      - bash
      - formatter
  - name: Prettier
    description: Polyglot code formatter.
    docs: https://prettier.io/docs/
    repo: https://github.com/prettier/prettier
    packages:
      homebrew: prettier
    tags:
      - formatter
      - javascript
      - typescript
      - json
      - yaml
      - markdown
      - css
      - html
      - markdown
      - scss
      - pluggable
  - name: Source Tree
    repo:
      github: https://github.com/GNOME/meld
    packages:
      homebrew:
        - sourcetree
    tags:
      - git client
      - gui
  - name: uv
    description: Python version, package, environment, and project manager.
    docs: https://docs.astral.sh/uv/
    repo:
      github: https://github.com/astral-sh/uv
    packages:
      homebrew: uv
    tags:
      - version manager
      - package manager
      - environment manager
      - project manager
      - script runner
      - command runner
      - build tool
      - python
vscode:
  extensions:
    - name: GitHub Copilot Chat
      id: GitHub.copilot-chat
      github: https://github.com/microsoft/vscode-copilot-chat
      marketplace: https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat
      tags:
        - ai assistant
    - name: GitHub Pull Requests
      id: github.vscode-pull-request-github
      github: https://github.com/Microsoft/vscode-pull-request-github
      marketplace: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github
      tags:
        - version control
    - name: Jupyter Extension for Visual Studio Code
      id: ms-toolsai.jupyter
      github: https://github.com/Microsoft/vscode-jupyter
      marketplace: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
      tags:
        - notebook support
        - python
    - name: Python extension for Visual Studio Code
      id: ms-python.python
      github: https://github.com/Microsoft/vscode-python
      marketplace: https://marketplace.visualstudio.com/items?itemName=ms-python.python
      tags:
        - language support
        - python
