applications:
  - name: Conda
    description: Python version and package manager.
    docs: https://www.anaconda.com/docs/getting-started/miniconda/main
    repo:
      github: https://github.com/conda/conda
    packages:
      homebrew: miniconda
    tags:
      - version manager
      - package manager
      - environment manager
  - name: uv
    description: Python version, package, environment, and project manager.
    docs: https://docs.astral.sh/uv/
    repo:
      github: https://github.com/astral-sh/uv
    packages:
      homebrew: uv
    tags:
      - version manager
      - package manager
      - environment manager
      - project manager
      - script runner
      - command runner
      - build tool
vscode:
  extensions:
    - name: Jupyter Extension for Visual Studio Code
      id: ms-toolsai.jupyter
      github: https://github.com/Microsoft/vscode-jupyter
      marketplace: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
      tags:
        - notebook support
        - python
    - name: Python extension for Visual Studio Code
      id: ms-python.python
      github: https://github.com/Microsoft/vscode-python
      marketplace: https://marketplace.visualstudio.com/items?itemName=ms-python.python
      tags:
        - language support
        - python
