- name: Install Rosetta 2 (macOS).
  ansible.builtin.shell:
    cmd: softwareupdate --install-rosetta --agree-to-license

- name: Install applications of infrastructure role (macOS).
  homebrew:
    name: '{{ app.packages.homebrew }}'
    state: present
  loop: '{{ applications }}'
  loop_control:
    loop_var: app
