- name: Install Rosetta 2 (macOS).
  ansible.builtin.command:
    cmd: softwareupdate --install-rosetta --agree-to-license
    creates: /Library/Apple/usr/libexec/oah

- name: Install applications of infrastructure role (macOS).
  community.general.homebrew:
    name: '{{ app.packages.homebrew }}'
    state: present
  loop: '{{ infrastructure_applications }}'
  loop_control:
    loop_var: app
