infrastructure_applications:
  - name: Amazon Web Services CLI
    docs: https://docs.aws.amazon.com/cli/
    repo:
      github: https://github.com/aws/aws-cli
    packages:
      homebrew: awscli
    tags:
      - command line tools
      - aws

  - name: Docker Desktop
    packages:
      homebrew: docker-desktop
    tags:
      - command line tools
      - containers
      - docker

  - name: Helm
    repo:
      github: https://github.com/helm/helm
    packages:
      homebrew: helm
    tags:
      - command line tools
      - containers
      - kubernetes
      - package management

  - name: Helmfile
    repo:
      github: https://github.com/helmfile/helmfile
    packages:
      homebrew: helmfile
    tags:
      - command line tools
      - containers
      - kubernetes
      - package management

  - name: kubectl
    repo:
      github: https://github.com/kubernetes/kubectl
    packages:
      homebrew: kubectl
    tags:
      - command line tools
      - kubernetes
      - cluster management

  - name: kustomize
    repo:
      github: https://github.com/kubernetes-sigs/kustomize
    packages:
      homebrew: kustomize
    tags:
      - command line tools
      - kubernetes
      - cluster management

  - name: minikube
    repo:
      github: https://github.com/kubernetes/minikube
    packages:
      homebrew: minikube
    tags:
      - command line tools
      - containers
      - kubernetes
      - cluster management

  - name: OpenTofu
    docs: https://opentofu.org/docs/
    repo: https://github.com/opentofu/opentofu
    packages:
      homebrew: opentofu
    tags:
      - command line tools
      - infrastructure provisioning
      - infrastructure as code
      - terraform alternative
      - open source

  - name: Terraform
    docs: https://developer.hashicorp.com/terraform
    repo:
      github: https://github.com/hashicorp/terraform
    packages:
      homebrew: terraform
    tags:
      - command line tools
      - infrastructure provisioning
      - infrastructure as code

  - name: Tilt
    repo:
      github: https://github.com/tilt-dev/tilt
    packages:
      homebrew: tilt
    tags:
      - command line tools
      - containers
      - development
      - environment management

infrastructure_vscode:
  extensions:
    - name: Container Tools for Visual Studio Code
      id: ms-azuretools.vscode-containers
      github: https://github.com/microsoft/vscode-containers
      marketplace: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-containers
      tags:
        - containers
        - language support
        - container explorer
        - image explorer
        - registry explorer
        - volume explorer
        - network explorer
        - dockerfile support
        - docker-compose support
        - ms-azuretools.vscode-docker replacement

    - name: Visual Studio Code Kubernetes Tools
      id: ms-kubernetes-tools.vscode-kubernetes-tools
      github: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools
      marketplace: https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools
      tags:
        - containers
        - docker support
        - helm
        - kubernetes
        - language support
        - cluster management
        - podman support
