- name: Install development applications (macOS).
  community.general.homebrew:
    name: '{{ app.packages.homebrew }}'
    state: present
  loop: '{{ development_applications }}'
  loop_control:
    loop_var: app
