- name: Install applications of communications role (macOS).
  community.general.homebrew:
    name: '{{ app.packages.homebrew }}'
    state: present
  loop: '{{ communications_applications }}'
  loop_control:
    loop_var: app
