- name: Install terminal tooling (macOS).
  community.general.homebrew:
    name: '{{ app.packages.homebrew }}'
    state: present
  loop: '{{ terminal_applications }}'
  loop_control:
    loop_var: app
