---
- name: Install Micro text-editor (macOS)
  when: ansible_facts['os_family'] == "Darwin"
  homebrew:
    name: micro
    state: present

- name: Install Aspell for Micro text-editor (macOS)
  when: ansible_facts['os_family'] == "Darwin"
  homebrew:
    name: aspell
    state: present
