applications:
  - name: Brave Web browser
    repo:
      github: https://github.com/brave/brave-browser
    packages:
      homebrew: brave-browser
    tags:
      - web browser
      - open source
      - chromium derivative

  - name: Bruno
    description: Lightweight alternative to Postman/Insomnia.
    repo: https://github.com/usebruno/bruno
    packages:
      homebrew: bruno
    tags:
      - API client
      - REST client
      - GraphQL client
      - development
      - API testing
      - websocket client
      - open source

  - name: Slack
    description: Team communication and collaboration platform
    packages:
      homebrew: slack
    tags:
      - instant messaging
      - video conferencing
      - desktop sharing
      - closed source

  - name: Zoom
    description: Video communication and virtual meeting platform
    packages:
      homebrew: zoom
    tags:
      - closed source
      - video conferencing
      - desktop sharing
